# Generated by Django 2.2 on 2021-06-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_dragon_riders_that_like_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.TextField(default='admin@yeah.gov'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='password',
            field=models.TextField(default='password'),
            preserve_default=False,
        ),
    ]
